### ISSUE TITLE
Suggestion: include examples using `rows`

### ISSUE THREAD

**Issue by turicas** [briandconnelly/BEACONToolkit#1]
Hello, everybody. First of all, thanks for this good work!
I'd like to present to you a command-line tool I'm working on called [rows](https://github.com/turicas/rows) -- with it is easy to print the CSV data, query it using SQL (!), convert from or to other formats (like HTML, XLS, XLSX etc.) and you can also use it in your Python software as a library; it has internal algorithms to detect and convert column types (like strings, integers, floats, dates etc.) and will preserve it during conversion.
No matter the format, rows just do the job -- the same way!
Hope you enjoy it. :)

**Comment by briandconnelly** [comment]
This toolkit/introduction is a few years old and is not going to be updated. Thanks for the suggestion, though! I'm excited to try out rows on my own!
